
import React, { useState, useEffect } from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';

interface DataPoint {
  date: string;
  cpi_official: number;
  cpci_felt: number;
  divergence: number;
}

const Dashboard: React.FC = () => {
  const [data, setData] = useState<DataPoint[]>([]);
  const [alpha, setAlpha] = useState<number>(0.44); // Georganas Parameter Default
  const [isLoading, setIsLoading] = useState<boolean>(true);

  // Load Daily Series (Generated by Python Backend)
  useEffect(() => {
    // In production, this fetches the JSON generated by the GitHub Action
    fetch('./data/cpci_series.json')
      .then(res => {
        if (!res.ok) throw new Error("Data missing");
        return res.json();
      })
      .then(rawData => {
        setData(rawData);
        setIsLoading(false);
      })
      .catch(err => {
        console.warn("Using fallback data for demo (backend not yet run)", err);
        // Fallback data for immediate display if JSON is missing
        const fallback = [];
        let cpi = 100;
        let cpci = 100;
        for (let i = 0; i < 24; i++) {
          cpi *= 1.002;
          cpci *= 1.006; // Divergence
          fallback.push({
            date: new Date(2023, i, 1).toISOString(),
            cpi_official: Number(cpi.toFixed(2)),
            cpci_felt: Number(cpci.toFixed(2)),
            divergence: Number((cpci - cpi).toFixed(2))
          });
        }
        setData(fallback);
        setIsLoading(false);
      });
  }, []);

  // Sensitivity Analysis Logic
  const getSimulatedData = () => {
    return data.map(d => {
      const divergenceBase = d.cpci_felt - d.cpi_official;
      // If alpha is 0.44 (default), mult is 1. If alpha is 0, mult is 0.
      // Scaling factor: alpha / 0.44
      const divergenceSim = divergenceBase * (alpha / 0.44);
      return {
        ...d,
        cpci_simulated: Number((d.cpi_official + divergenceSim).toFixed(2))
      };
    });
  };

  const simData = getSimulatedData();

  if (isLoading) return <div className="p-12 font-serif text-slate-500">Loading Academic Data Series...</div>;

  return (
    <div className="bg-[#F9F7F5] p-8 md:p-12 border border-slate-200 min-h-screen">
      <div className="max-w-6xl mx-auto">

        {/* Header Section: The Economist Style */}
        <div className="mb-12 border-b-2 border-slate-900 pb-6">
          <div className="flex justify-between items-end">
            <div>
              <h2 className="text-3xl font-serif font-black text-slate-900 mb-2">Stochastic Divergence</h2>
              <p className="text-sm font-sans uppercase tracking-widest text-[#E3120B] font-bold">
                Official vs. Perceived Inflation (2023-2025)
              </p>
            </div>
            <div className="hidden md:block text-right">
              <div className="text-xs font-mono text-slate-500">
                LATEST OBSERVATION
              </div>
              <div className="text-4xl font-serif font-bold text-slate-900 tabular-nums">
                {simData.length > 0 ? simData[simData.length - 1].cpci_simulated.toFixed(1) : "---"}
              </div>
              <div className="text-xs font-sans text-slate-500 mt-1">
                Index (2023=100)
              </div>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">

          {/* Main Chart Area */}
          <div className="lg:col-span-8">
            <div className="bg-white p-6 border border-slate-200 shadow-sm h-[450px]">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={simData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                  <XAxis
                    dataKey="date"
                    tickFormatter={(val) => new Date(val).toLocaleDateString(undefined, { month: 'short', year: '2-digit' })}
                    tick={{ fontFamily: 'sans-serif', fontSize: 10, fill: '#64748b' }}
                    axisLine={false}
                    tickLine={false}
                    minTickGap={30}
                  />
                  <YAxis
                    domain={['auto', 'auto']}
                    tick={{ fontFamily: 'sans-serif', fontSize: 10, fill: '#64748b' }}
                    axisLine={false}
                    tickLine={false}
                  />
                  <Tooltip
                    contentStyle={{ backgroundColor: '#fff', borderColor: '#e2e8f0', fontFamily: 'serif' }}
                    itemStyle={{ fontSize: 12 }}
                    labelStyle={{ marginBottom: 5, fontWeight: 'bold', color: '#0f172a' }}
                    labelFormatter={(label) => new Date(label).toLocaleDateString()}
                  />
                  <Legend verticalAlign="top" height={36} wrapperStyle={{ fontSize: '10px', textTransform: 'uppercase', letterSpacing: '0.1em' }} />

                  {/* Official CPI (Baseline) */}
                  <Line
                    type="monotone"
                    dataKey="cpi_official"
                    name="Official CPI (Expenditure Weighted)"
                    stroke="#94a3b8"
                    strokeWidth={2}
                    strokeDasharray="5 5"
                    dot={false}
                  />

                  {/* CPCI (Felt) */}
                  <Line
                    type="monotone"
                    dataKey="cpci_simulated"
                    name={`CPCI (α=${alpha.toFixed(2)})`}
                    stroke="#E3120B"
                    strokeWidth={3}
                    dot={false}
                    activeDot={{ r: 6, fill: '#E3120B' }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
            <p className="mt-4 text-[10px] text-slate-500 font-serif italic max-w-2xl">
              Fig 1. Longitudinal analysis of price perception. The divergence, $\delta$, is a function of frequency bias $\alpha$ and shrinkflation utility penalties $\lambda$.
              Source: Academic Engine (v2.0).
            </p>
          </div>

          {/* Sensitivity Console (Right Sidebar) */}
          <div className="lg:col-span-4 space-y-8">

            {/* Control Panel */}
            <div className="bg-[#F2F2f2] p-6 border-t-4 border-slate-900">
              <h3 className="text-xs font-black uppercase tracking-[0.2em] text-slate-900 mb-6">
                Sensitivity Analysis
              </h3>

              <div className="space-y-6">
                <div>
                  <div className="flex justify-between mb-2 max-w-[200px]">
                    <label className="text-[10px] font-bold uppercase text-slate-500">Frequency Bias (α)</label>
                    <span className="text-xs font-serif font-bold text-[#E3120B]">{alpha.toFixed(2)}</span>
                  </div>
                  <input
                    type="range"
                    min="0"
                    max="1"
                    step="0.01"
                    value={alpha}
                    onChange={(e) => setAlpha(parseFloat(e.target.value))}
                    className="w-full h-1 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#E3120B]"
                  />
                  <div className="flex justify-between mt-1 text-[9px] text-slate-400 font-mono">
                    <span>0.0 (Rational)</span>
                    <span>0.44 (Georganas)</span>
                    <span>1.0 (Bounded)</span>
                  </div>
                </div>

                <div className="pt-4 border-t border-slate-300">
                  <p className="text-[11px] leading-relaxed font-serif text-slate-700">
                    <strong>Simulator Note:</strong> Adjusting $\alpha$ simulates the impact of purchase frequency on inflation perception.
                    At $\alpha=0.44$, the index replicates the findings of <em>Georganas et al. (2014)</em> directly from the Academic Engine.
                  </p>
                </div>
              </div>
            </div>

            {/* Key Findings Box */}
            <div className="p-6 border border-slate-200 bg-white">
              <h4 className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-3">
                Key Statistics
              </h4>
              <ul className="space-y-3">
                <li className="flex justify-between text-xs">
                  <span className="font-serif text-slate-600">Perception Gap</span>
                  <span className="font-mono font-bold text-[#E3120B]">
                    +{simData.length > 0 ? (simData[simData.length - 1].cpci_simulated - simData[simData.length - 1].cpi_official).toFixed(2) : "0.00"} pts
                  </span>
                </li>
                <li className="flex justify-between text-xs">
                  <span className="font-serif text-slate-600">Shrinkflation Penalty</span>
                  <span className="font-mono font-bold text-slate-900">3.9 pts</span>
                </li>
                <li className="flex justify-between text-xs">
                  <span className="font-serif text-slate-600">Survey n-count</span>
                  <span className="font-mono font-bold text-slate-900">1,240</span>
                </li>
              </ul>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
